@startuml name Dynamic
title Dynamic Architecture: Temperature monitoring flow

box "PersistentMemory" #LightSlateGray
    database "EEPROM" as ee
end box

box "Temperature-Sensing" #LightBlue
participant "TempSensor" as Ts 
participant "ADC" as adc
end box

!pragma teoz true
box "µC Domain"
    participant "Hw variation" as hw
    participant "Timer-100µsec" as int
    box "Adc Control" #LightCoral
        participant "adcIsrhandling" as Isr
        participant "adcSampling" as sample
    end box  


    box "Temperature Monitoring" #LightGreen
        participant "TempMonitor" as tm
        participant "gpio" as gp
    end box
end box    



== Initialization Mode ==
ee --> hw: Read Hw variation during each powercycle init phase via I2C
hw --> sample: Provide HW version info
== Normal Mode ==
Ts --> adc: Analog values are transmitted to adc
int --> Isr: Isr is triggered every 100msec \n when timer expires 
Isr -> Isr: Store in an array \n recieved adc values
note over Isr, sample
After recieving 10 adc samples
end note
Isr --> sample: Trigger Adc sampling
activate sample
sample -> sample: Perform \n moving average \n of 10 adc samples
destroy sample
sample --> tm: Trigger Monitoring
activate tm
tm --> sample: fetch averaged adc value
tm -> tm : Convert adc value \n to temperature based on the HW
tm -> tm : Compare against the  temperature ranges 
tm -> gp: Trigger appropriate GPIO \n to represent temperature range
destroy tm
@enduml
