@startuml staticarch
title System under Development
package "TemperatureMontoring" {
    [eepromAccess] as ea
    package "adcControl" as adc{
    [adcInterruptHandler] as adcIsr
    [adcSampling]
    }
    [tempMonitor] as tmp
    [gpioControl] as gpio
}

ea --> tmp
adc --> tmp
tmp --> gpio
@enduml
